import type { WorldContent, Project, Category } from "../types";

export const PROJECTS: Project[] = [
  {
    id: "exp1",
    name: "PETRONAS Digital",
    desc: "Serverless ingestion + retrieval augmented generation used by 700+ employees.",
    url: "#",
    role: "Software Engineering Intern",
    tags: ["Azure", "Kafka", "RAG"],
    x: 0,
    y: 0,
  },
  {
    id: "exp2",
    name: "CS4450 Computer Networks",
    desc: "Taught computer Networks at Cornell.",
    url: "#",
    role: "Undergraduate TA",
    tags: ["TCP/IP", "UDP"],
    x: 0,
    y: 0,
  },
  {
    id: "exp2",
    name: "CS4450 Computer Networks",
    desc: "Taught computer Networks at Cornell.",
    url: "#",
    role: "Undergraduate TA",
    tags: ["TCP/IP", "UDP"],
    x: 0,
    y: 0,
  },
  {
    id: "exp3",
    name: "Environmental Data Governance Initiative",
    desc: "Built EPA Violation Data Platform for NGO.",
    url: "#",
    role: "Backend Developer",
    tags: ["Geo", "Streamlit", "ETL"],
    x: 0,
    y: 0,
  },
  {
    id: "exp4",
    name: "Cornell Development in Games",
    desc: "Led a 20 person cross-functional Team.",
    url: "#",
    role: "Backend Developer",
    tags: ["Game Dev"],
    x: 0,
    y: 0,
  },
  {
    id: "game1",
    name: "Trigger Happy",
    desc: "Multiplayer card game on iOS and Android.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "game2",
    name: "Grub Bug",
    desc: "Action packed delivery game.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "game3",
    name: "Ambrosia",
    desc: "Bullet hell with Critter Evolution.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "game4",
    name: "Loop De Coop",
    desc: "Made for GMTK Game Jam 2025.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "game5",
    name: "Tilly's Critter Command",
    desc: "2.5D Third Person RTS.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "game6",
    name: "Knead for Speed",
    desc: "A Puzzle game about scent trails.",
    url: "#",
    role: "Game Designer/Developer",
    tags: ["CUGL", "Prediction", "Rollback-lite"],
    x: 0,
    y: 0,
  },
  {
    id: "proj1",
    name: "Searchless Chess with Transformers",
    desc: "Trained a transformer to play chess.",
    url: "#",
    role: "Backend Developer",
    tags: ["Geo", "Streamlit", "ETL"],
    x: 0,
    y: 0,
  },
  {
    id: "proj2",
    name: "Secure KV-Store",
    desc: "A multi-client secure key-value store with ACLs and multiple-clients on the command line.",
    url: "#",
    role: "Backend Developer",
    tags: ["Geo", "Streamlit", "ETL"],
    x: 0,
    y: 0,
  },
  {
    id: "proj3",
    name: "Class Rooster",
    desc: "A class ranking app.",
    url: "#",
    role: "Backend Developer",
    tags: ["Geo", "Streamlit", "ETL"],
    x: 0,
    y: 0,
  },
  {
    id: "proj4",
    name: "TED Finds",
    desc: "A information retrieval app.",
    url: "#",
    role: "Backend Developer",
    tags: ["Geo", "Streamlit", "ETL"],
    x: 0,
    y: 0,
  },
];

const CATEGORIES: Category[] = [
  {
    id: "cat-Projects",
    name: "Projects",
    x: 6,
    y: 2,
    spawnRadius: 4,
    minSpacing: 2,
    rerollOnStep: false,
    projectIds: ["proj1", "proj2", "proj3", "proj4"],
  },
  {
    id: "cat-Games",
    name: "Games",
    x: 2,
    y: 8,
    spawnRadius: 5,
    minSpacing: 3,
    rerollOnStep: false, // step again = toggle off
    projectIds: ["game1", "game2", "game3", "game4", "game5", "game6"],
  },
  {
    id: "cat-Experience",
    name: "Experience",
    x: 9,
    y: 7,
    spawnRadius: 4,
    projectIds: ["exp1", "exp2", "exp3"],
  },
];

export const WORLD_CONTENT: WorldContent = {
  obstacles: [
    [5, 5],
    [5, 6],
    [5, 7],
    [6, 7],
    [7, 7],
  ],
  playerStart: [2, 2],
  heroTile: [1, 1], // ← stepping onto this shows your hero panel
  categories: CATEGORIES,
  projects: PROJECTS,
};
